# common args added in parser
common:
  algorithm_name: mappo
  # num_train_envs: 128
  num_torch_threads: 4
  n_rollout_threads: 8
  # num_eval_envs: 32
  # eval_episodes: 32
  # eval_interval: 50
  # n_eval_rollout_threads: 8
  # num_env_splits: 2
  log_interval: 1

  episode_length: 50
  num_env_steps: 1.0e+6
  ppo_epoch: 5

  use_wandb: True
  # wandb_project: bridge_ar
  # wandb_group: check
  num_mini_batch: 2

  lr: 7.0e-4
  critic_lr: 7.0e-4
  gain: 0.01

  use_ReLU: False
  use_centralized_V: False
  use_recurrent_policy: False

# special cfg for policy
# TODO
policy:
  type: bridge_ar
  args:
    hidden_dim: 64
    num_dense_layers: 2
    num_rnn_layers: 0
    random_order: True
    n_agents: 2
    agent_specific_obs: True

# special cfg for env
# TODO
environment:
  type: metadrive
  args:
    base:
      num_agents: 2
      agent_specific_obs: True
      share_reward: True
      episode_length: 30
      num_random_blocks: 0
      use_ally_id: False
      use_agent_id: False